### ISSUE TITLE
parser module has no attribute 'get_parser'

### ISSUE THREAD

**Issue by bilthon** [nikcub/cexbot#3]
This is what I get when I try to run the cexbot-cli with python 2.7.6

```
Nelsons-MacBook-Pro:cexbot nelson$ python cexbot-cli -h
Traceback (most recent call last):
  File "cexbot-cli", line 6, in <module>
    cexbot.command_utils.run_cl(sys.argv)
  File "/Users/nelson/Development/Python/cexbot/cexbot/command_utils.py", line 108, in run_cl
    raise SystemExit(main(sys.argv))
  File "/Users/nelson/Development/Python/cexbot/cexbot/command_utils.py", line 12, in main
    args = parser.get_parser()
AttributeError: 'module' object has no attribute 'get_parser'
```

If I try to run it with python3 I get stuck (I think ) before:

```
Nelsons-MacBook-Pro:cexbot nelson$ python3 cexbot-cli -h
Traceback (most recent call last):
  File "cexbot-cli", line 4, in <module>
    import cexbot.command_utils
  File "/Users/nelson/Development/Python/cexbot/cexbot/__init__.py", line 56
    print file_path
```

**Comment by craigatron** [comment]
It looks like some code got moved into a parser module, but that module was never added to the repo.

**Comment by pincy** [comment]
I can verify this.
Any updates on this?
I really would like to try this piece of software

**Comment by theag3nt** [comment]
I think the last commit was in the middle of some reorganizations and some code never made it to the repo.

I forked it and fixed a couple of errors and tried to replace missing code, but I didn't test all functions. Give it a try if you want: theag3nt/cexbot@2c5c0821c2

I might write a bot myself, but not in the near future. If you have some suggestions feel free to contact me.
